# items.py
from typing import Optional, Tuple
from rapidfuzz import process

# ---------------------------------------------------------------------------
#  League of Legends Item Data
#  Each entry is a readable name and the corresponding numeric item ID.
# ---------------------------------------------------------------------------
ITEMS = [
    {"name": "Boots", "id": "1001"},
    {"name": "Faerie Charm", "id": "1004"},
    {"name": "Rejuvenation Bead", "id": "1006"},
    {"name": "Giant's Belt", "id": "1011"},
    {"name": "Cloak of Agility", "id": "1018"},
    {"name": "Blasting Wand", "id": "1026"},
    {"name": "Sapphire Crystal", "id": "1027"},
    {"name": "Ruby Crystal", "id": "1028"},
    {"name": "Cloth Armor", "id": "1029"},
    {"name": "Chain Vest", "id": "1031"},
    {"name": "Null-Magic Mantle", "id": "1033"},
    {"name": "Emberknife", "id": "1035"},
    {"name": "Long Sword", "id": "1036"},
    {"name": "Pickaxe", "id": "1037"},
    {"name": "BF Sword", "id": "1038"},
    {"name": "Hailblade", "id": "1039"},
    {"name": "Obsidian Edge", "id": "1040"},
    {"name": "Dagger", "id": "1042"},
    {"name": "Recurve Bow", "id": "1043"},
    {"name": "Amplifying Tome", "id": "1052"},
    {"name": "Vampiric Scepter", "id": "1053"},
    {"name": "Doran's Shield", "id": "1054"},
    {"name": "Doran's Blade", "id": "1055"},
    {"name": "Doran's Ring", "id": "1056"},
    {"name": "Negatron Cloak", "id": "1057"},
    {"name": "Needlessly Large Rod", "id": "1058"},
    {"name": "Dark Seal", "id": "1082"},
    {"name": "Cull", "id": "1083"},
    {"name": "Health Potion", "id": "2003"},
    {"name": "Total Biscuit of Everlasting Will", "id": "2010"},
    {"name": "Kircheis Shard", "id": "2015"},
    {"name": "Refillable Potion", "id": "2031"},
    {"name": "Corrupting Potion", "id": "2033"},
    {"name": "Guardian's Horn", "id": "2051"},
    {"name": "Poro-Snax", "id": "2052"},
    {"name": "Control Ward", "id": "2055"},
    {"name": "Shurelya's Battlesong", "id": "2065"},
    {"name": "Elixir of Iron", "id": "2138"},
    {"name": "Elixir of Sorcery", "id": "2139"},
    {"name": "Elixir of Wrath", "id": "2140"},
    {"name": "Minion Dematerializer", "id": "2403"},
    {"name": "Commencing Stopwatch", "id": "2419"},
    {"name": "Stopwatch", "id": "2420"},
    {"name": "Broken Stopwatch", "id": "2424"},
    {"name": "Slightly Magical Footwear", "id": "2422"},
    {"name": "Perfectly Timed Stopwatch", "id": "2423"},
    {"name": "Evenshroud", "id": "3001"},
    {"name": "Archangel's Staff", "id": "3003"},
    {"name": "Manamune", "id": "3004"},
    {"name": "Berserker's Greaves", "id": "3006"},
    {"name": "Boots of Swiftness", "id": "3009"},
    {"name": "Chemtech Putrifier", "id": "3011"},
    {"name": "Sorcerer's Shoes", "id": "3020"},
    {"name": "Glacial Buckler", "id": "3024"},
    {"name": "Guardian Angel", "id": "3026"},
    {"name": "Infinity Edge", "id": "3031"},
    {"name": "Mortal Reminder", "id": "3033"},
    {"name": "Last Whisper", "id": "3035"},
    {"name": "Lord Dominik's Regards", "id": "3036"},
    {"name": "Seraph's Embrace", "id": "3040"},
    {"name": "Mejai's Soulstealer", "id": "3041"},
    {"name": "Muramana", "id": "3042"},
    {"name": "Phage", "id": "3044"},
    {"name": "Phantom Dancer", "id": "3046"},
    {"name": "Plated Steelcaps", "id": "3047"},
    {"name": "Zeke's Convergence", "id": "3050"},
    {"name": "Hearthbound Axe", "id": "3051"},
    {"name": "Sterak's Gage", "id": "3053"},
    {"name": "Sheen", "id": "3057"},
    {"name": "Spirit Visage", "id": "3065"},
    {"name": "Winged Moonplate", "id": "3066"},
    {"name": "Kindlegem", "id": "3067"},
    {"name": "Sunfire Aegis", "id": "3068"},
    {"name": "Tear of the Goddess", "id": "3070"},
    {"name": "Black Cleaver", "id": "3071"},
    {"name": "Bloodthirster", "id": "3072"},
    {"name": "Ravenous Hydra", "id": "3074"},
    {"name": "Thornmail", "id": "3075"},
    {"name": "Bramble Vest", "id": "3076"},
    {"name": "Tiamat", "id": "3077"},
    {"name": "Trinity Force", "id": "3078"},
    {"name": "Warden's Mail", "id": "3082"},
    {"name": "Warmog's Armor", "id": "3083"},
    {"name": "Runaan's Hurricane", "id": "3085"},
    {"name": "Zeal", "id": "3086"},
    {"name": "Rabadon's Deathcap", "id": "3089"},
    {"name": "Wit's End", "id": "3091"},
    {"name": "Rapid Firecannon", "id": "3094"},
    {"name": "Stormrazor", "id": "3095"},
    {"name": "Lich Bane", "id": "3100"},
    {"name": "Banshee's Veil", "id": "3102"},
    {"name": "Aegis of the Legion", "id": "3105"},
    {"name": "Redemption", "id": "3107"},
    {"name": "Fiendish Codex", "id": "3108"},
    {"name": "Knight's Vow", "id": "3109"},
    {"name": "Frozen Heart", "id": "3110"},
    {"name": "Mercury's Treads", "id": "3111"},
    {"name": "Guardian's Orb", "id": "3112"},
    {"name": "Aether Wisp", "id": "3113"},
    {"name": "Forbidden Idol", "id": "3114"},
    {"name": "Nashor's Tooth", "id": "3115"},
    {"name": "Rylai's Crystal Scepter", "id": "3116"},
    {"name": "Mobility Boots", "id": "3117"},
    {"name": "Winter's Approach", "id": "3119"},
    {"name": "Fimbulwinter", "id": "3121"},
    {"name": "Executioner's Calling", "id": "3123"},
    {"name": "Guinsoo's Rageblade", "id": "3124"},
    {"name": "Caulfield's Warhammer", "id": "3133"},
    {"name": "Serrated Dirk", "id": "3134"},
    {"name": "Void Staff", "id": "3135"},
    {"name": "Mercurial Scimitar", "id": "3139"},
    {"name": "Quicksilver Sash", "id": "3140"},
    {"name": "Youmuu's Ghostblade", "id": "3142"},
    {"name": "Randuin's Omen", "id": "3143"},
    {"name": "Hextech Alternator", "id": "3145"},
    {"name": "Hextech Rocketbelt", "id": "3152"},
    {"name": "Blade of The Ruined King", "id": "3153"},
    {"name": "Hexdrinker", "id": "3155"},
    {"name": "Maw of Malmortius", "id": "3156"},
    {"name": "Zhonya's Hourglass", "id": "3157"},
    {"name": "Ionian Boots of Lucidity", "id": "3158"},
    {"name": "Morellonomicon", "id": "3165"},
    {"name": "Guardian's Blade", "id": "3177"},
    {"name": "Umbral Glaive", "id": "3179"},
    {"name": "Hullbreaker", "id": "3181"},
    {"name": "Guardian's Hammer", "id": "3184"},
    {"name": "Locket of the Iron Solari", "id": "3190"},
    {"name": "Seeker's Armguard", "id": "3191"},
    {"name": "Gargoyle Stoneplate", "id": "3193"},
    {"name": "Spectre's Cowl", "id": "3211"},
    {"name": "Mikael's Blessing", "id": "3222"},
    {"name": "Scarecrow Effigy", "id": "3330"},
    {"name": "Stealth Ward", "id": "3340"},
    {"name": "Farsight Alteration", "id": "3363"},
    {"name": "Oracle Lens", "id": "3364"},
    {"name": "Your Cut", "id": "3400"},
    {"name": "Ardent Censer", "id": "3504"},
    {"name": "Essence Reaver", "id": "3508"},
    {"name": "Eye of the Herald", "id": "3513"},
    {"name": "Kalista's Black Spear", "id": "3600"},
    {"name": "Dead Man's Plate", "id": "3742"},
    {"name": "Titanic Hydra", "id": "3748"},
    {"name": "Crystalline Bracer", "id": "3801"},
    {"name": "Lost Chapter", "id": "3802"},
    {"name": "Edge of Night", "id": "3814"},
    {"name": "Spellthief's Edge", "id": "3850"},
    {"name": "Frostfang", "id": "3851"},
    {"name": "Shard of True Ice", "id": "3853"},
    {"name": "Steel Shoulderguards", "id": "3854"},
    {"name": "Runesteel Spaulders", "id": "3855"},
    {"name": "Pauldrons of Whiterock", "id": "3857"},
    {"name": "Relic Shield", "id": "3858"},
    {"name": "Targon's Buckler", "id": "3859"},
    {"name": "Bulwark of the Mountain", "id": "3860"},
    {"name": "Spectral Sickle", "id": "3862"},
    {"name": "Harrowing Crescent", "id": "3863"},
    {"name": "Black Mist Scythe", "id": "3864"},
    {"name": "Oblivion Orb", "id": "3916"},
    {"name": "Imperial Mandate", "id": "4005"},
    {"name": "Force of Nature", "id": "4401"},
    {"name": "The Golden Spatula", "id": "4403"},
    {"name": "Horizon Focus", "id": "4628"},
    {"name": "Cosmic Drive", "id": "4629"},
    {"name": "Blighting Jewel", "id": "4630"},
    {"name": "Verdant Barrier", "id": "4632"},
    {"name": "Riftmaker", "id": "4633"},
    {"name": "Leeching Leer", "id": "4635"},
    {"name": "Night Harvester", "id": "4636"},
    {"name": "Demonic Embrace", "id": "4637"},
    {"name": "Watchful Wardstone", "id": "4638"},
    {"name": "Bandleglass Mirror", "id": "4642"},
    {"name": "Vigilant Wardstone", "id": "4643"},
    {"name": "Crown of the Shattered Queen", "id": "4644"},
    {"name": "Shadowflame", "id": "4645"},
    {"name": "Ironspike Whip", "id": "6029"},
    {"name": "Silvermere Dawn", "id": "6035"},
    {"name": "Death's Dance", "id": "6333"},
    {"name": "Chempunk Chainsword", "id": "6609"},
    {"name": "Staff of Flowing Water", "id": "6616"},
    {"name": "Moonstone Renewer", "id": "6617"},
    {"name": "Goredrinker", "id": "6630"},
    {"name": "Stridebreaker", "id": "6631"},
    {"name": "Divine Sunderer", "id": "6632"},
    {"name": "Liandry's Anguish", "id": "6653"},
    {"name": "Luden's Tempest", "id": "6655"},
    {"name": "Everfrost", "id": "6656"},
    {"name": "Bami's Cinder", "id": "6660"},
    {"name": "Frostfire Gauntlet", "id": "6662"},
    {"name": "Turbo Chemtank", "id": "6664"},
    {"name": "Noonquiver", "id": "6670"},
    {"name": "Galeforce", "id": "6671"},
    {"name": "Kraken Slayer", "id": "6672"},
    {"name": "Immortal Shieldbow", "id": "6673"},
    {"name": "Navori Quickblades", "id": "6675"},
    {"name": "The Collector", "id": "6676"},
    {"name": "Rageknife", "id": "6677"},
    {"name": "Duskblade of Draktharr", "id": "6691"},
    {"name": "Eclipse", "id": "6692"},
    {"name": "Prowler's Claw", "id": "6693"},
    {"name": "Serylda's Grudge", "id": "6694"},
    {"name": "Serpent's Fang", "id": "6695"},
    {"name": "Axiom Arc", "id": "6696"},
    {"name": "Anathema's Chains", "id": "8001"},
    {"name": "Abyssal Mask", "id": "8020"},
]

# Pre-built lookup for O(1) ID retrieval after fuzzy match
ITEM_NAME_TO_ID = {item["name"]: item["id"] for item in ITEMS}
ALL_NAMES = list(ITEM_NAME_TO_ID.keys())


def find_item(user_input: str) -> Optional[Tuple[str, str]]:
    """
    Fuzzy-match user input to the static ITEMS list.
    Returns a tuple of (exact_name, item_id) or None if nothing close enough.
    """
    # RapidFuzz handles case insensitivity if we give it a processor
    result = process.extractOne(
        user_input,
        ALL_NAMES,
        processor=lambda s: s.lower(),
        score_cutoff=70,
    )
    if result:
        match, score, _ = result
        return match, ITEM_NAME_TO_ID[match]
    return None
