# items.py
from typing import Optional, Tuple
from rapidfuzz import process

# ---------------------------------------------------------------------------
#  League of Legends Item Data
#  Each entry is a readable name and the corresponding numeric item ID.
# ---------------------------------------------------------------------------
ITEMS = [
    {"name": "Boots", "id": "1001"},
    {"name": "Faerie Charm", "id": "1004"},
    {"name": "Rejuvenation Bead", "id": "1006"},
    {"name": "Giant's Belt", "id": "221011"},
    {"name": "Cloak of Agility", "id": "1018"},
    {"name": "Blasting Wand", "id": "221026"},
    {"name": "Sapphire Crystal", "id": "1027"},
    {"name": "Ruby Crystal", "id": "1028"},
    {"name": "Cloth Armor", "id": "1029"},
    {"name": "Chain Vest", "id": "221031"},
    {"name": "Null-Magic Mantle", "id": "1033"},
    {"name": "Emberknife", "id": "1035"},
    {"name": "Long Sword", "id": "1036"},
    {"name": "Pickaxe", "id": "1037"},
    {"name": "B. F. Sword", "id": "221038"},
    {"name": "Hailblade", "id": "1039"},
    {"name": "Obsidian Edge", "id": "1040"},
    {"name": "Dagger", "id": "1042"},
    {"name": "Recurve Bow", "id": "221043"},
    {"name": "Amplifying Tome", "id": "1052"},
    {"name": "Vampiric Scepter", "id": "221053"},
    {"name": "Doran's Shield", "id": "1054"},
    {"name": "Doran's Blade", "id": "1055"},
    {"name": "Doran's Ring", "id": "1056"},
    {"name": "Negatron Cloak", "id": "221057"},
    {"name": "Needlessly Large Rod", "id": "221058"},
    {"name": "Dark Seal", "id": "1082"},
    {"name": "Cull", "id": "1083"},
    {"name": "Scorchclaw Pup", "id": "1107"},
    {"name": "Gustwalker Hatchling", "id": "1106"},
    {"name": "Mosstomper Seedling", "id": "1105"},
    {"name": "Eye of the Herald", "id": "3513"},
    {"name": "Hubris", "id": "6697"},
    {"name": "Penetrating Bullets", "id": "1500"},
    {"name": "Fortification", "id": "1521"},
    {"name": "Reinforced Armor", "id": "1506"},
    {"name": "Warden's Eye", "id": "1503"},
    {"name": "Vanguard", "id": "1504"},
    {"name": "Overcharged", "id": "1523"},
    {"name": "Anti-tower Socks", "id": "1508"},
    {"name": "Gusto", "id": "1509"},
    {"name": "Phreakish Gusto", "id": "1510"},
    {"name": "Super Mech Armor", "id": "1511"},
    {"name": "Super Mech Power Field", "id": "1512"},
    {"name": "Turret Plating", "id": "1515"},
    {"name": "Structure Bounty", "id": "1519"},
    {"name": "OvererchargedHA", "id": "1520"},
    {"name": "Tower Power-Up", "id": "1522"},
    {"name": "Health Potion", "id": "2003"},
    {"name": "Total Biscuit of Everlasting Will", "id": "2010"},
    {"name": "Kircheis Shard", "id": "2015"},
    {"name": "Steel Sigil", "id": "2019"},
    {"name": "The Brutalizer", "id": "2020"},
    {"name": "Tunneler", "id": "2021"},
    {"name": "Glowing Mote", "id": "222022"},
    {"name": "Refillable Potion", "id": "2031"},
    {"name": "Corrupting Potion", "id": "2033"},
    {"name": "Guardian's Amulet", "id": "2049"},
    {"name": "Guardian's Shroud", "id": "2050"},
    {"name": "Guardian's Horn", "id": "222051"},
    {"name": "Poro-Snax", "id": "2052"},
    {"name": "Control Ward", "id": "2055"},
    {"name": "Stealth Ward", "id": "3340"},
    {"name": "Shurelya's Battlesong", "id": "322065"},
    {"name": "Elixir of Iron", "id": "2138"},
    {"name": "Elixir of Sorcery", "id": "2139"},
    {"name": "Elixir of Wrath", "id": "2140"},
    {"name": "Cappa Juice", "id": "222141"},
    {"name": "Juice of Power", "id": "2142"},
    {"name": "Juice of Vitality", "id": "2143"},
    {"name": "Juice of Haste", "id": "2144"},
    {"name": "Lucky Dice", "id": "2145"},
    {"name": "Enhanced Lucky Dice", "id": "2146"},
    {"name": "Elixir of Skill", "id": "2150"},
    {"name": "Elixir of Avarice", "id": "2151"},
    {"name": "Elixir of Force", "id": "2152"},
    {"name": "Bandle Juice of Power", "id": "2161"},
    {"name": "Bandle Juice of Vitality", "id": "2162"},
    {"name": "Bandle Juice of Haste", "id": "2163"},
    {"name": "Stat Bonus", "id": "220000"},
    {"name": "Legendary Fighter Item", "id": "220001"},
    {"name": "Legendary Marksman Item", "id": "220002"},
    {"name": "Legendary Assassin Item", "id": "220003"},
    {"name": "Legendary Mage Item", "id": "220004"},
    {"name": "Legendary Tank Item", "id": "220005"},
    {"name": "Legendary Support Item", "id": "220006"},
    {"name": "Prismatic Item", "id": "220007"},
    {"name": "Anvil Voucher", "id": "220008"},
    {"name": "Gold Stat Anvil Voucher", "id": "220009"},
    {"name": "Prismatic Stat Voucher", "id": "220010"},
    {"name": "Bravery Voucher", "id": "220011"},
    {"name": "Unending Despair", "id": "2502"},
    {"name": "Blackfire Torch", "id": "2503"},
    {"name": "Kaenic Rookern", "id": "2504"},
    {"name": "Evenshroud", "id": "3001"},
    {"name": "Trailblazer", "id": "323002"},
    {"name": "Archangel's Staff", "id": "323003"},
    {"name": "Manamune", "id": "323004"},
    {"name": "Ghostcrawlers", "id": "3005"},
    {"name": "Berserker's Greaves", "id": "3006"},
    {"name": "Boots of Swiftness", "id": "3009"},
    {"name": "Chemtech Putrifier", "id": "3011"},
    {"name": "Sorcerer's Shoes", "id": "3020"},
    {"name": "Guardian Angel", "id": "3026"},
    {"name": "Infinity Edge", "id": "3031"},
    {"name": "Yun Tal Wildarrows", "id": "3032"},
    {"name": "Mortal Reminder", "id": "3033"},
    {"name": "Lord Dominik's Regards", "id": "3036"},
    {"name": "Atma's Reckoning", "id": "663039"},
    {"name": "Seraph's Embrace", "id": "323040"},
    {"name": "Muramana", "id": "323042"},
    {"name": "Phantom Dancer", "id": "3046"},
    {"name": "Plated Steelcaps", "id": "3047"},
    {"name": "Zeke's Convergence", "id": "323050"},
    {"name": "Sterak's Gage", "id": "3053"},
    {"name": "Sheen", "id": "3057"},
    {"name": "Spirit Visage", "id": "3065"},
    {"name": "Kindlegem", "id": "3067"},
    {"name": "Sunfire Aegis", "id": "3068"},
    {"name": "Black Cleaver", "id": "3071"},
    {"name": "Bloodthirster", "id": "3072"},
    {"name": "Experimental Hexplate", "id": "3073"},
    {"name": "Ravenous Hydra", "id": "3074"},
    {"name": "Thornmail", "id": "323075"},
    {"name": "Trinity Force", "id": "3078"},
    {"name": "Heartsteel", "id": "3084"},
    {"name": "Runaan's Hurricane", "id": "3085"},
    {"name": "Statikk Shiv", "id": "3087"},
    {"name": "Rabadon's Deathcap", "id": "3089"},
    {"name": "Wit's End", "id": "3091"},
    {"name": "Rapid Firecannon", "id": "3094"},
    {"name": "Stormrazor", "id": "3095"},
    {"name": "Lich Bane", "id": "3100"},
    {"name": "Banshee's Veil", "id": "3102"},
    {"name": "Aegis of the Legion", "id": "3105"},
    {"name": "Redemption", "id": "323107"},
    {"name": "Knight's Vow", "id": "323109"},
    {"name": "Frozen Heart", "id": "323110"},
    {"name": "Mercury's Treads", "id": "3111"},
    {"name": "Guardian's Orb", "id": "3112"},
    {"name": "Nashor's Tooth", "id": "3115"},
    {"name": "Rylai's Crystal Scepter", "id": "3116"},
    {"name": "Malignance", "id": "3118"},
    {"name": "Winter's Approach", "id": "323119"},
    {"name": "Fimbulwinter", "id": "323121"},
    {"name": "Guinsoo's Rageblade", "id": "3124"},
    {"name": "Void Staff", "id": "3135"},
    {"name": "Cryptbloom", "id": "3137"},
    {"name": "Mercurial Scimitar", "id": "3139"},
    {"name": "Youmuu's Ghostblade", "id": "3142"},
    {"name": "Randuin's Omen", "id": "3143"},
    {"name": "Hextech Gunblade", "id": "663146"},
    {"name": "Hextech Rocketbelt", "id": "3152"},
    {"name": "Blade of The Ruined King", "id": "3153"},
    {"name": "Maw of Malmortius", "id": "3156"},
    {"name": "Zhonya's Hourglass", "id": "3157"},
    {"name": "Ionian Boots of Lucidity", "id": "3158"},
    {"name": "Spear of Shojin", "id": "3161"},
    {"name": "Morellonomicon", "id": "3165"},
    {"name": "Zephyr", "id": "663172"},
    {"name": "Guardian's Blade", "id": "3177"},
    {"name": "Hullbreaker", "id": "3181"},
    {"name": "Guardian's Hammer", "id": "3184"},
    {"name": "Guardian's Dirk", "id": "223185"},
    {"name": "Locket of the Iron Solari", "id": "323190"},
    {"name": "Gargoyle Stoneplate", "id": "663193"},
    {"name": "Mikael's Blessing", "id": "323222"},
    {"name": "Terminus", "id": "3302"},
    {"name": "Ardent Censer", "id": "3504"},
    {"name": "Essence Reaver", "id": "3508"},
    {"name": "Dead Man's Plate", "id": "3742"},
    {"name": "Titanic Hydra", "id": "3748"},
    {"name": "Edge of Night", "id": "3814"},
    {"name": "Spectral Cutlass", "id": "4004"},
    {"name": "Imperial Mandate", "id": "4005"},
    {"name": "Force of Nature", "id": "4401"},
    {"name": "The Golden Spatula", "id": "664403"},
    {"name": "Horizon Focus", "id": "4628"},
    {"name": "Cosmic Drive", "id": "4629"},
    {"name": "Riftmaker", "id": "4633"},
    {"name": "Night Harvester", "id": "4636"},
    {"name": "Demonic Embrace", "id": "4637"},
    {"name": "Crown of the Shattered Queen", "id": "664644"},
    {"name": "Shadowflame", "id": "4645"},
    {"name": "Stormsurge", "id": "4646"},
    {"name": "Silvermere Dawn", "id": "6035"},
    {"name": "Death's Dance", "id": "6333"},
    {"name": "Chempunk Chainsword", "id": "6609"},
    {"name": "Sundered Sky", "id": "6610"},
    {"name": "Staff of Flowing Water", "id": "6616"},
    {"name": "Moonstone Renewer", "id": "6617"},
    {"name": "Echoes of Helia", "id": "6620"},
    {"name": "Dawncore", "id": "6621"},
    {"name": "Goredrinker", "id": "6630"},
    {"name": "Stridebreaker", "id": "6631"},
    {"name": "Divine Sunderer", "id": "6632"},
    {"name": "Liandry's Anguish", "id": "226653"},
    {"name": "Luden's Companion", "id": "6655"},
    {"name": "Everfrost", "id": "6656"},
    {"name": "Rod of Ages", "id": "6657"},
    {"name": "Iceborn Gauntlet", "id": "6662"},
    {"name": "Hollow Radiance", "id": "6664"},
    {"name": "Jak'Sho, The Protean", "id": "6665"},
    {"name": "Radiant Virtue", "id": "6667"},
    {"name": "Galeforce", "id": "6671"},
    {"name": "Kraken Slayer", "id": "6672"},
    {"name": "Immortal Shieldbow", "id": "6673"},
    {"name": "Navori Flickerblades", "id": "226675"},
    {"name": "The Collector", "id": "667666"},
    {"name": "Duskblade of Draktharr", "id": "6691"},
    {"name": "Eclipse", "id": "6692"},
    {"name": "Prowler's Claw", "id": "6693"},
    {"name": "Serylda's Grudge", "id": "6694"},
    {"name": "Serpent's Fang", "id": "6695"},
    {"name": "Axiom Arc", "id": "6696"},
    {"name": "Profane Hydra", "id": "6698"},
    {"name": "Voltaic Cyclosword", "id": "6699"},
    {"name": "Opportunity", "id": "6701"},
    {"name": "Anathema's Chains", "id": "8001"},
    {"name": "Wooglet's Witchcap", "id": "228002"},
    {"name": "Deathblade", "id": "228003"},
    {"name": "Adaptive Helm", "id": "228004"},
    {"name": "Obsidian Cleaver", "id": "228005"},
    {"name": "Sanguine Blade", "id": "228006"},
    {"name": "Runeglaive", "id": "228008"},
    {"name": "Abyssal Mask", "id": "8020"},
    {"name": "Minion Dematerializer", "id": "2403"},
    {"name": "Seeker's Armguard", "id": "2420"},
    {"name": "Shattered Armguard", "id": "2421"},
    {"name": "Slightly Magical Footwear", "id": "2422"},
    {"name": "Overlord's Bloodmail", "id": "447111"},
    {"name": "Fated Ashes", "id": "2508"},
    {"name": "Symbiotic Soles", "id": "3010"},
    {"name": "Chalice of Blessing", "id": "3012"},
    {"name": "Synchronized Souls", "id": "3013"},
    {"name": "Lifewell Pendant", "id": "3023"},
    {"name": "Glacial Buckler", "id": "3024"},
    {"name": "Last Whisper", "id": "3035"},
    {"name": "Mejai's Soulstealer", "id": "3041"},
    {"name": "Phage", "id": "3044"},
    {"name": "Hearthbound Axe", "id": "3051"},
    {"name": "Winged Moonplate", "id": "3066"},
    {"name": "Tear of the Goddess", "id": "323070"},
    {"name": "Bramble Vest", "id": "3076"},
    {"name": "Tiamat", "id": "3077"},
    {"name": "Warden's Mail", "id": "3082"},
    {"name": "Warmog's Armor", "id": "443083"},
    {"name": "Zeal", "id": "3086"},
    {"name": "Fiendish Codex", "id": "3108"},
    {"name": "Aether Wisp", "id": "3113"},
    {"name": "Forbidden Idol", "id": "3114"},
    {"name": "Mobility Boots", "id": "3117"},
    {"name": "Executioner's Calling", "id": "3123"},
    {"name": "Deathfire Grasp", "id": "3128"},
    {"name": "Sword of the Divine", "id": "663060"},
    {"name": "Caulfield's Warhammer", "id": "3133"},
    {"name": "Serrated Dirk", "id": "3134"},
    {"name": "Quicksilver Sash", "id": "3140"},
    {"name": "Scout's Slingshot", "id": "3144"},
    {"name": "Hextech Alternator", "id": "3145"},
    {"name": "Haunting Guise", "id": "3147"},
    {"name": "Hexdrinker", "id": "3155"},
    {"name": "Swiftmarch", "id": "3170"},
    {"name": "Crimson Lucidity", "id": "3171"},
    {"name": "Gunmetal Greaves", "id": "3172"},
    {"name": "Chainlaced Crushers", "id": "3173"},
    {"name": "Armored Advance", "id": "3174"},
    {"name": "Spellslinger's Shoes", "id": "3175"},
    {"name": "Forever Forward", "id": "3176"},
    {"name": "Umbral Glaive", "id": "3179"},
    {"name": "Spectre's Cowl", "id": "3211"},
    {"name": "Scarecrow Effigy", "id": "3330"},
    {"name": "Arcane Sweeper", "id": "3348"},
    {"name": "Lucent Singularity", "id": "3349"},
    {"name": "Farsight Alteration", "id": "3363"},
    {"name": "Oracle Lens", "id": "3364"},
    {"name": "Small Party Favor", "id": "3398"},
    {"name": "Party Favor", "id": "3399"},
    {"name": "Your Cut", "id": "3400"},
    {"name": "Rite Of Ruin", "id": "3430"},
    {"name": "Kalista's Black Spear", "id": "3600"},
    {"name": "Crystalline Bracer", "id": "3801"},
    {"name": "Lost Chapter", "id": "3802"},
    {"name": "Catalyst of Aeons", "id": "3803"},
    {"name": "Spellthief's Edge", "id": "3850"},
    {"name": "Frostfang", "id": "3851"},
    {"name": "Shard of True Ice", "id": "3853"},
    {"name": "Steel Shoulderguards", "id": "3854"},
    {"name": "Runesteel Spaulders", "id": "3855"},
    {"name": "Pauldrons of Whiterock", "id": "3857"},
    {"name": "Relic Shield", "id": "3858"},
    {"name": "Targon's Buckler", "id": "3859"},
    {"name": "Bulwark of the Mountain", "id": "3860"},
    {"name": "Spectral Sickle", "id": "3862"},
    {"name": "Harrowing Crescent", "id": "3863"},
    {"name": "Black Mist Scythe", "id": "3864"},
    {"name": "World Atlas", "id": "3865"},
    {"name": "Runic Compass", "id": "3866"},
    {"name": "Bounty of Worlds", "id": "3867"},
    {"name": "Celestial Opposition", "id": "3869"},
    {"name": "Dream Maker", "id": "3870"},
    {"name": "Zaz'Zak's Realmspike", "id": "3871"},
    {"name": "Solstice Sleigh", "id": "3876"},
    {"name": "Bloodsong", "id": "3877"},
    {"name": "Oblivion Orb", "id": "3916"},
    {"name": "Lifeline", "id": "4003"},
    {"name": "Bloodletter's Curse", "id": "8010"},
    {"name": "Sword of Blossoming Dawn", "id": "664011"},
    {"name": "Sin Eater", "id": "4012"},
    {"name": "Lightning Braid", "id": "4013"},
    {"name": "Frozen Mallet", "id": "4014"},
    {"name": "Perplexity", "id": "4015"},
    {"name": "Wordless Promise", "id": "4016"},
    {"name": "Hellfire Hatchet", "id": "4017"},
    {"name": "Innervating Locket", "id": "447104"},
    {"name": "Darksteel Talons", "id": "443054"},
    {"name": "Fulmination", "id": "443055"},
    {"name": "Demon King's Crown", "id": "663056"},
    {"name": "Shield of Molten Stone", "id": "663058"},
    {"name": "Cloak of Starry Night", "id": "663059"},
    {"name": "Force Of Entropy", "id": "443061"},
    {"name": "Sanguine Gift", "id": "443062"},
    {"name": "Eleisa's Miracle", "id": "443063"},
    {"name": "Talisman Of Ascension", "id": "443064"},
    {"name": "Hamstringer", "id": "443069"},
    {"name": "Turbo Chemtank", "id": "443079"},
    {"name": "Twin Mask", "id": "443080"},
    {"name": "Hexbolt Companion", "id": "443081"},
    {"name": "Reaper's Toll", "id": "443090"},
    {"name": "Mirage Blade", "id": "447100"},
    {"name": "Gambler's Blade", "id": "667101"},
    {"name": "Reality Fracture", "id": "447102"},
    {"name": "Hemomancer's Helm", "id": "447103"},
    {"name": "Empyrean Promise", "id": "447105"},
    {"name": "Dragonheart", "id": "447106"},
    {"name": "Decapitator", "id": "447107"},
    {"name": "Runecarver", "id": "447108"},
    {"name": "Cruelty", "id": "667109"},
    {"name": "Moonflair Spellblade", "id": "447110"},
    {"name": "Flesheater", "id": "667112"},
    {"name": "Detonation Orb", "id": "447113"},
    {"name": "Reverberation", "id": "447114"},
    {"name": "Regicide", "id": "447115"},
    {"name": "Kinkou Jitte", "id": "447116"},
    {"name": "Pyromancer's Cloak", "id": "447118"},
    {"name": "Lightning Rod", "id": "447119"},
    {"name": "Diamond-Tipped Spear", "id": "447120"},
    {"name": "Twilight's Edge", "id": "447121"},
    {"name": "Black Hole Gauntlet", "id": "447122"},
    {"name": "Puppeteer", "id": "447123"},
    {"name": "Blighting Jewel", "id": "4630"},
    {"name": "Verdant Barrier", "id": "4632"},
    {"name": "Leeching Leer", "id": "4635"},
    {"name": "Watchful Wardstone", "id": "4638"},
    {"name": "Stirring Wardstone", "id": "4641"},
    {"name": "Bandleglass Mirror", "id": "4642"},
    {"name": "Vigilant Wardstone", "id": "4643"},
    {"name": "Ironspike Whip", "id": "6029"},
    {"name": "Veigar's Talisman of Ascension", "id": "663064"},
    {"name": "Liandry's Torment", "id": "6653"},
    {"name": "Bami's Cinder", "id": "6660"},
    {"name": "Noonquiver", "id": "6670"},
    {"name": "Navori Flickerblade", "id": "6675"},
    {"name": "Rageknife", "id": "6677"},
    {"name": "Rectrix", "id": "6690"},
    {"name": "Shield of the Rakkor", "id": "6700"},
    {"name": "Scouting Ahead", "id": "6702"},
    {"name": "Gangplank Placeholder", "id": "7050"},
    {"name": "Locked Weapon Slot", "id": "9168"},
    {"name": "Cyclonic Slicers", "id": "9171"},
    {"name": "YuumiBot", "id": "9172"},
    {"name": "Radiant Field", "id": "9173"},
    {"name": "Statikk Sword", "id": "9174"},
    {"name": "Lioness's Lament", "id": "9175"},
    {"name": "Gatling Bunny-Guns", "id": "9176"},
    {"name": "Searing Shortbow", "id": "9177"},
    {"name": "The Annihilator", "id": "9178"},
    {"name": "Battle Bunny Crossbow", "id": "9179"},
    {"name": "UwU Blaster", "id": "9180"},
    {"name": "Vortex Glove", "id": "9181"},
    {"name": "Blade-o-rang", "id": "9183"},
    {"name": "Bunny Mega-Blast", "id": "9184"},
    {"name": "Anti-Shark Sea Mine", "id": "9185"},
    {"name": "T.I.B.B.E.R.S", "id": "9187"},
    {"name": "Ani-Mines", "id": "9188"},
    {"name": "Final City Transit", "id": "9189"},
    {"name": "Echoing Batblades", "id": "9190"},
    {"name": "Paw Print Poisoner", "id": "9192"},
    {"name": "Iceblast Armor", "id": "9193"},
    {"name": "Unceasing Cyclone", "id": "9271"},
    {"name": "YuumiBot_Final_FINAL", "id": "9272"},
    {"name": "Explosive Embrace", "id": "9273"},
    {"name": "Prumbis's Electrocarver", "id": "9274"},
    {"name": "Enveloping Light", "id": "9275"},
    {"name": "Double Bun-Bun Barrage", "id": "9276"},
    {"name": "Evolved Embershot", "id": "9277"},
    {"name": "Animapocalypse", "id": "9278"},
    {"name": "Bunny Prime Ballista", "id": "9279"},
    {"name": "OwO Blaster", "id": "9280"},
    {"name": "Tempest's Gauntlet", "id": "9281"},
    {"name": "Quad-o-rang", "id": "9283"},
    {"name": "Rapid Rabbit Raindown", "id": "9284"},
    {"name": "Neverending Mobstomper", "id": "9285"},
    {"name": "T.I.B.B.E.R.S (B.E.E.G Edition)", "id": "9287"},
    {"name": "Jinx's Tri-Namite", "id": "9288"},
    {"name": "FC Limited Express", "id": "9289"},
    {"name": "Vayne's Chromablades", "id": "9290"},
    {"name": "Bearfoot Chem-Dispenser", "id": "9292"},
    {"name": "Deep Freeze", "id": "9293"},
    {"name": "Meow Meow", "id": "9300"},
    {"name": "Shield Slam", "id": "9301"},
    {"name": "Sound Wave", "id": "9302"},
    {"name": "Pillory Swipe", "id": "9303"},
    {"name": "Steel Tempest", "id": "9304"},
    {"name": "Tentacle Slam", "id": "9305"},
    {"name": "Winged Dagger", "id": "9306"},
    {"name": "Guiding Hex", "id": "9307"},
    {"name": "Bunny Hop", "id": "9308"},
    {"name": "Battle Cat Barrage", "id": "9400"},
    {"name": "Light of the Lion", "id": "9401"},
    {"name": "Anima Echo", "id": "9402"},
    {"name": "Savage Slice", "id": "9403"},
    {"name": "Wandering Storms", "id": "9404"},
    {"name": "Grizzly Smash", "id": "9405"},
    {"name": "Lover's Ricochet", "id": "9406"},
    {"name": "Hopped-Up Hex", "id": "9407"},
    {"name": "Carrot Crash", "id": "9408"},
]

# Pre-built lookup for O(1) ID retrieval after fuzzy match
ITEM_NAME_TO_ID = {item["name"]: item["id"] for item in ITEMS}
ALL_NAMES = list(ITEM_NAME_TO_ID.keys())


def find_item(user_input: str) -> Optional[Tuple[str, str]]:
    """
    Fuzzy-match user input to the static ITEMS list.
    Returns a tuple of (exact_name, item_id) or None if nothing close enough.
    """
    # RapidFuzz handles case insensitivity if we give it a processor
    result = process.extractOne(
        user_input,
        ALL_NAMES,
        processor=lambda s: s.lower(),
        score_cutoff=70,
    )
    if result:
        match, score, _ = result
        return match, ITEM_NAME_TO_ID[match]
    return None
